export const fakeCities =
[
    'Chicago (US)',
    'Moranbah (AU)',
    'Watford (UK)',
    'Hobart (AU)',
    'Whitman (US)',
    'Fort Pierce (US)',
    'Stanley (UK)',
    'Kirkby Stephen (UK)',
    'Shefford (UK)',
    'Las Cruces (US)',
    'Oroville (US)',
    'Minden (US)',
    'Ogdensburg (US)',
    'Walsenburg (US)',
    'Mamaroneck (US)',
    'Belvidere (US)',
    'Halstead (UK)',
    'Settle (UK)',
    'Mackinaw City (US)',
    'Wichita (US)',
    'Ecorse (US)',
    'Enfield (UK)',
    'Brooklyn (US)',
    'Weehawken (US)',
    'Mentor (US)',
    'Lydd (UK)',
    'Placentia (CA)',
    'Faversham (UK)',
    'Vincennes (US)',
    'Mineola (US)',
    'Homer (US)',
    'Palm Beach (US)',
    'Preston (UK)',
    'Cleburne (US)',
    'Bushey (UK)',
    'Ponteland (UK)',
    'L (CA)',
    'Gosport (UK)',
    'Chorley (UK)',
    'New Madrid (US)',
    'St Austell (UK)',
    'Fairhaven (US)',
    'Uniontown (US)',
    'Rumford (US)',
    'Higham Ferrers (UK)',
    'New Haven (US)',
    'Grand Forks (US)',
    'Cambridge (CA)',
    'Portland (UK)',
    'South Brent (UK)',
    'Canyon (US)',
    'Durham (UK)',
    'Bangor (UK)',
    'Gunnison (US)',
    'Charleville (AU)',
    'Auburn (US)',
    'Bryan (US)',
    'Ferndown (UK)',
    'Ilminster (UK)',
    'Ardmore (US)',
    'Fordbridge (UK)',
    'Stirling (UK)',
    'Kirton-in-Lindsey (UK)',
    'Weston (US)',
    'Jonesborough (US)',
    'Coalville (UK)',
    'Stafford (UK)',
    'Eastpointe (US)',
    'Babylon (US)',
    'Saint Paul (US)',
    'Derry (US)',
    'Darien (US)',
    'Winchester (US)',
    'Peru (US)',
    'Virden (US)',
    'Wickwar (UK)',
    'Berlin (US)',
    'Saint-Hubert (CA)',
    'Arlington Heights (US)',
    'Brigg (UK)',
    'Bordentown (US)',
    'Gold Coast (AU)',
    'Harbour Grace (CA)',
    'Irthling (UK)',
    'Tiverton (UK)',
    'Burgess Hill (UK)',
    'Ossett (UK)',
    'Phoenixville (US)',
    'North York (CA)',
    'Moundsville (US)',
    'Socorro (US)',
    'Sun Valley (US)',
    'New York City (US)',
    'Caistor (UK)',
    'Milford (US)',
    'Bury (UK)',
    'Bridlington (UK)',
    'Har (UK)',
    'Levittown (US)',
    'Rockhampton (AU)'
];