export const fakeCountries =
[
    'Scotland',
    'Equatorial Guinea',
    'Republic of Macedonia',
    'Serbia',
    'The Gambia',
    'Haiti',
    'Jamaica',
    'Svalbard and Jan Mayen',
    'Marshall Islands',
    'Italy',
    'Niue',
    'Swaziland',
    'Montserrat',
    'Thailand',
    'Kenya',
    'Ethiopia',
    'Lebanon',
    'Jersey',
    'Mali',
    'Sierra Leone',
    'East Timor',
    'Tonga',
    'Papua New Guinea',
    'Chile',
    'Bulgaria',
    'United States',
    'Belarus',
    'Vanuatu',
    'United Kingdom',
    'Cape Verde',
    'Latvia',
    'Malaysia',
    'Sweden',
    'Iran',
    'Sao Tome and Principe',
    'Cyprus',
    'Holy See',
    'Somalia',
    'French Polynesia',
    'Saudi Arabia',
    'United Arab Emirates',
    'Bhutan',
    'United States Minor Outlying Island',
    'Austria',
    'Tunisia',
    'American Samoa',
    'Turkmenistan',
    'San Marino',
    'Greece',
    'Isle of Man',
    'South Africa',
    'Northern Ireland',
    'Puerto Rico',
    'Norway',
    'Palau',
    'Denmark',
    'Seychelles',
    'Qatar',
    'Ivory Coast',
    'Grenada',
    'Andorra',
    'Zambia',
    'Saint Helena',
    'Spain',
    'Saint Kitts and Nevis',
    'Bolivia',
    'Netherlands',
    'Liechtenstein',
    'French Guiana',
    'Argentina',
    'Nauru',
    'Maldives',
    'Mayotte',
    'Senegal',
    'Costa Rica',
    'Israel',
    'Tajikistan',
    'Pitcairn Islands',
    'Hungary',
    'Central African Republic',
    'Republic of the Congo',
    'Slovenia',
    'Myanmar',
    'Cayman Islands',
    'Eritrea',
    'Albania',
    'Kyrgyzstan',
    'Suriname',
    'Nicaragua',
    'Indonesia',
    'Iceland',
    'Colombia',
    'Hong Kong',
    'France',
    'Uruguay',
    'Gibraltar',
    'Palestine',
    'Japan',
    'Falkland Islands',
    'Moldova'
];