export const fakeReviews =
[,
    "They throw cabbage that turns your brain into emotional baggage.",
    "It was getting dark, and we weren’t there yet.",
    "The memory we used to share is no longer coherent.",
    "She saw the brake lights, but not in time.",
    "It dawned on her that others could make her happier, but only she could make herself happy.",
    "He was the type of guy who liked Christmas lights on his house in the middle of July.",
    "He fumbled in the darkness looking for the light switch, but when he finally found it there was someone already there.",
    "It didn't make sense unless you had the power to eat colors.",
    "As the rental car rolled to a stop on the dark road, her fear increased by the moment.",
    "The thick foliage and intertwined vines made the hike nearly impossible.",
    "Every manager should be able to recite at least ten nursery rhymes backward.",
    "Doris enjoyed tapping her nails on the table to annoy everyone.",
    "Let me help you with your baggage.",
    "Truth in advertising and dinosaurs with skateboards have much in common.",
    "They ran around the corner to find that they had traveled back in time.",
    "Combines are no longer just for farms.",
    "I come from a tribe of head-hunters, so I will never need a shrink.",
    "He was so preoccupied with whether or not he could that he failed to stop to consider if he should.",
    "A suit of armor provides excellent sun protection on hot days.",
    "It's not often you find a soggy banana on the street.",
    "He took one look at what was under the table and noped the hell out of there.",
    "He drank life before spitting it out.",
    "While on the first date he accidentally hit his head on the beam.",
    "He wore the surgical mask in public not to keep from catching a virus, but to keep people away from him.",
    "Lets all be unique together until we realise we are all the same.",
    "Please tell me you don't work in a morgue.",
    "He stomped on his fruit loops and thus became a cereal killer.",
    "The sign said road work ahead so he decided to speed up.",
    "You're unsure whether or not to trust him, but very thankful that you wore a turtle neck.",
    "It is grossly unfair to suggest that the school was responsible for the accident.",
    "After exploring the abandoned building, he started to believe in ghosts.",
    "It was the best sandcastle he had ever seen.",
    "She had the gift of being able to paint songs.",
    "All they could see was the blue water surrounding their sailboat.",
    "We will not allow you to bring your pet armadillo along.",
    "When motorists sped in and out of traffic, all she could think of was those in need of a transplant.",
    "I just wanted to tell you I could see the love you have for your child by the way you look at her.",
    "Sometimes it is better to just walk away from things and go back to them later when you’re in a better frame of mind.",
    "The snow-covered path was no help in finding his way out of the backcountry.",
    "Standing on one's head at job interviews forms a lasting impression.",
    "Pantyhose and heels are an interesting choice of attire for the beach.",
    "I'd rather be a bird than a fish.",
    "The irony of the situation wasn't lost on anyone in the room.",
    "There's an art to getting your way, and spitting olive pits across the table isn't it.",
    "She did her best to help him.",
    "The elephant didn't want to talk about the person in the room.",
    "I may struggle with geography, but I'm sure I'm somewhere around here.",
    "It's much more difficult to play tennis with a bowling ball than it is to bowl with a tennis ball.",
    "If any cop asks you where you were, just say you were visiting Kansas.",
    "People generally approve of dogs eating cat food but not cats eating dog food.",
    "He drank life before spitting it out.",
    "The sun had set and so had his dreams.",
    "You're good at English when you know the difference between a man eating chicken and a man-eating chicken.",
    "She advised him to come back at once.",
    "I hear that Nancy is very pretty.",
    "She was disgusted he couldn’t tell the difference between lemonade and limeade.",
    "The rain pelted the windshield as the darkness engulfed us.",
    "I am my aunt's sister's daughter.",
    "Going from child, to childish, to childlike is only a matter of time.",
    "Nothing is as cautiously cuddly as a pet porcupine.",
    "I am counting my calories, yet I really want dessert.",
    "It had been sixteen days since the zombies first attacked.",
    "It's a skateboarding penguin with a sunhat.",
    "Every manager should be able to recite at least ten nursery rhymes backward.",
    "While on the first date he accidentally hit his head on the beam.",
    "The trick to getting kids to eat anything is to put ketchup on it.",
    "She was the type of girl who wanted to live in a pink house.",
    "The pizza smells delicious.",
    "The green tea and avocado smoothie turned out exactly as would be expected.",
    "The shark-infested South Pine channel was the only way in or out.",
    "The truth is that you pay for your lifestyle in hours.",
    "Car safety systems have come a long way, but he was out to prove they could be outsmarted.",
    "The fox in the tophat whispered into the ear of the rabbit.",
    "Everyone says they love nature until they realize how dangerous she can be.",
    "I want more detailed information.",
    "Mrs Miller wants the entire house repainted.",
    "The secret ingredient to his wonderful life was crime.",
    "Nobody loves a pig wearing lipstick.",
    "Pantyhose and heels are an interesting choice of attire for the beach.",
    "Never underestimate the willingness of the greedy to throw you under the bus.",
    "I just wanted to tell you I could see the love you have for your child by the way you look at her.",
    "This book is sure to liquefy your brain.",
    "Truth in advertising and dinosaurs with skateboards have much in common.",
    "The blinking lights of the antenna tower came into focus just as I heard a loud snap.",
    "Random words in front of other random words create a random sentence.",
    "Each person who knows you has a different perception of who you are.",
    "The minute she landed she understood the reason this was a fly-over state.",
    "I covered my friend in baby oil.",
    "The pet shop stocks everything you need to keep your anaconda happy.",
    "She found his complete dullness interesting.",
    "You bite up because of your lower jaw.",
    "I think I will buy the red car, or I will lease the blue one.",
    "Smoky the Bear secretly started the fires.",
    "He realized there had been several deaths on this road, but his concern rose when he saw the exact number.",
    "As the years pass by, we all know owners look more and more like their dogs.",
    "We have a lot of rain in June.",
    "We will not allow you to bring your pet armadillo along.",
    "He invested some skill points in Charisma and Strength.",
    "Two more days and all his problems would be solved.",
    "Look on top of the refrigerator for the key.",
    "Every manager should be able to recite at least ten nursery rhymes backward.",
    "The pet shop stocks everything you need to keep your anaconda happy.",
    "I am happy to take your donation; any amount will be greatly appreciated.",
    "I met an interesting turtle while the song on the radio blasted away.",
    "I ate a sock because people on the Internet told me to.",
    "When he had to picnic on the beach, he purposely put sand in other people’s food.",
    "Italy is my favorite country; in fact, I plan to spend two weeks there next year.",
    "Eating eggs on Thursday for choir practice was recommended.",
    "Her daily goal was to improve on yesterday.",
    "The quick brown fox jumps over the lazy dog.",
    "The rain pelted the windshield as the darkness engulfed us.",
    "The shooter says goodbye to his love.",
    "There's an art to getting your way, and spitting olive pits across the table isn't it.",
    "I just wanted to tell you I could see the love you have for your child by the way you look at her.",
    "With a single flip of the coin, his life changed forever.",
    "This book is sure to liquefy your brain.",
    "Your girlfriend bought your favorite cookie crisp cereal but forgot to get milk.",
    "If my calculator had a history, it would be more embarrassing than my browser history.",
    "The tart lemonade quenched her thirst, but not her longing.",
    "He swore he just saw his sushi move.",
    "A song can make or ruin a person’s day if they let it get to them.",
    "For oil spots on the floor, nothing beats parking a motorbike in the lounge.",
    "He wondered if she would appreciate his toenail collection.",
    "They wandered into a strange Tiki bar on the edge of the small beach town.",
    "It's not often you find a soggy banana on the street.",
    "Rock music approaches at high velocity.",
    "Peanut butter and jelly caused the elderly lady to think about her past.",
    "He found the chocolate covered roaches quite tasty.",
    "You realize you're not alone as you sit in your bedroom massaging your calves after a long day of playing tug-of-war with Grandpa Joe in the hospital.",
    "He was 100% into fasting with her until he understood that meant he couldn't eat.",
    "The view from the lighthouse excited even the most seasoned traveler.",
    "Nobody has encountered an explosive daisy and lived to tell the tale.",
    "It was the scarcity that fueled his creativity.",
    "Pantyhose and heels are an interesting choice of attire for the beach.",
    "Iguanas were falling out of the trees.",
    "He waited for the stop sign to turn to a go sign.",
    "My Mum tries to be cool by saying that she likes all the same things that I do.",
    "The minute she landed she understood the reason this was a fly-over state.",
    "Nudist colonies shun fig-leaf couture.",
    "Two more days and all his problems would be solved.",
    "There's a message for you if you look up.",
    "He found a leprechaun in his walnut shell.",
    "Potato wedges probably are not best for relationships.",
    "The old apple revels in its authority.",
    "He was sure the Devil created red sparkly glitter.",
    "We need to rent a room for our party.",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "He was sitting in a trash can with high street class.",
    "Her scream silenced the rowdy teenagers.",
    "Love is not like pizza.",
    "He was 100% into fasting with her until he understood that meant he couldn't eat.",
    "She wore green lipstick like a fashion icon.",
    "He looked behind the door and didn't like what he saw.",
    "The Japanese yen for commerce is still well-known.",
    "I checked to make sure that he was still alive.",
    "I really want to go to work, but I am too sick to drive.",
    "It doesn't sound like that will ever be on my travel list.",
    "That was how he came to win $1 million.",
    "Nobody questions who built the pyramids in Mexico.",
    "The random sentence generator generated a random sentence about a random sentence.",
    "Going from child, to childish, to childlike is only a matter of time.",
    "I hear that Nancy is very pretty.",
    "A song can make or ruin a person’s day if they let it get to them.",
    "I was very proud of my nickname throughout high school but today- I couldn’t be any different to what my nickname was.",
    "It caught him off guard that space smelled of seared steak.",
    "Two seats were vacant.",
    "The father died during childbirth.",
    "I'm a great listener, really good with empathy vs sympathy and all that, but I hate people.",
    "He had reached the point where he was paranoid about being paranoid.",
    "The blinking lights of the antenna tower came into focus just as I heard a loud snap.",
    "Everyone was busy, so I went to the movie alone.",
    "Erin accidentally created a new universe.",
    "She did not cheat on the test, for it was not the right thing to do.",
    "I like to leave work after my eight-hour tea-break.",
    "I ate a sock because people on the Internet told me to.",
    "He swore he just saw his sushi move.",
    "He stepped gingerly onto the bridge knowing that enchantment awaited on the other side.",
    "Jeanne wished she has chosen the red button.",
    "In hopes of finding out the truth, he entered the one-room library.",
    "This is a Japanese doll.",
    "It dawned on her that others could make her happier, but only she could make herself happy.",
    "You bite up because of your lower jaw.",
    "The waitress was not amused when he ordered green eggs and ham.",
    "He ran out of money, so he had to stop playing poker.",
    "It's not often you find a soggy banana on the street.",
    "There was no ice cream in the freezer, nor did they have money to go to the store.",
    "She works two jobs to make ends meet; at least, that was her reason for not having time to join us.",
    "There's a reason that roses have thorns.",
    "The crowd yells and screams for more memes.",
    "I'm confused: when people ask me what's up, and I point, they groan.",
    "He used to get confused between soldiers and shoulders, but as a military man, he now soldiers responsibility.",
    "Love is not like pizza.",
    "It was the best sandcastle he had ever seen.",
    "Dan took the deep dive down the rabbit hole.",
    "The minute she landed she understood the reason this was a fly-over state.",
    "We had a three-course meal.",
    "The fact that there's a stairway to heaven and a highway to hell explains life well.",
    "They say that dogs are man's best friend, but this cat was setting out to sabotage that theory.",
    "Doris enjoyed tapping her nails on the table to annoy everyone.",
    "She had some amazing news to share but nobody to share it with."
];